include $(BUILD_DIR)/Header.mk

MODULE  := misc
SRC_DIR :=
DEFINE  :=
INCLUDE := -I../
LDFLAGS :=
LIBS    := -L$(LIBS_DIR)
EXECUTABLE_LDFLAGS += 
EXECUTABLE_LIBS := -lutils 


$(call build-target, static_library)

include $(BUILD_DIR)/Footer.mk

