include $(BUILD_DIR)/Header.mk

MODULE  := 
SRC_DIR := src
DEFINE  :=
INCLUDE := -Iinclude
LDFLAGS := 
LIBS    := -lavformat -lavcodec -lavutil -lavfilter -lswresample -lswscale -lSDL


$(call build-target, executable)


include $(BUILD_DIR)/Footer.mk
