include $(BUILD_DIR)/Header.mk

MODULE  := parse_config_file
SRC_DIR :=
DEFINE  :=
INCLUDE :=
LDFLAGS :=
LIBS    := -L$(LIBS_DIR)
EXECUTABLE_LDFLAGS := -Wl,-rpath="out/lib"
EXECUTABLE_LIBS := 


$(call build-target, executable)

include $(BUILD_DIR)/Footer.mk
