include $(BUILD_DIR)/Header.mk

MODULE  := 
SRC_DIR := 
DEFINE  :=
INCLUDE := -Iinclude
LDFLAGS :=  -pthread
LIBS    := -lGLESv2 -lEGL -lX11


$(call build-target, static_library)


include $(BUILD_DIR)/Footer.mk
