include $(BUILD_DIR)/Header.mk

MODULE  :=  
SRC_DIR :=
DEFINE  :=
INCLUDE := -Iinclude
LDFLAGS := 
LIBS    := -lavformat -lavcodec -lavutil -lavfilter -lswresample -lswscale -lSDL2 -lSDL2_image -lSDL2_ttf


$(call build-target, executable)


include $(BUILD_DIR)/Footer.mk
