include $(BUILD_DIR)/Header.mk

MODULE  := test_static_link
SRC_DIR :=
DEFINE  :=
CFLAGS  += 
CXXFLAGS  +=
INCLUDE :=
LDFLAGS :=
LIBS    := -L$(LIBS_DIR)
EXECUTABLE_LDFLAGS := -Wl,-rpath="out/lib"
EXECUTABLE_LIBS := 

$(call build-target, executable)

include $(BUILD_DIR)/Footer.mk
