
build_target clean:;

#BUILD_OBJ_DIR:=../build/objs/mbox
#target:$(BUILD_OBJ_DIR)
	#cd $< && qmake -nocache -r -spec linux-g++ ../../../mbox
	#$(MAKE) -C $<

#$(BUILD_OBJ_DIR):
	#mkdir $@

#clean:
	#$(MAKE) -C $(BUILD_OBJ_DIR) distclean
