include $(BUILD_DIR)/Header.mk

MODULE  := rtmpclient
SRC_DIR :=
DEFINE  :=
INCLUDE :=
LDFLAGS := 
LIBS    := -lavformat -lavcodec -lavutil -lavfilter -lswresample -lswscale -lrtmp


$(call build-target, executable)


include $(BUILD_DIR)/Footer.mk
