include $(BUILD_DIR)/Header.mk

MODULE  := 
SRC_DIR :=
DEFINE  :=
INCLUDE :=
LDFLAGS := 
LIBS    := -lavformat -lavcodec -lavutil -lavfilter -lswresample -lswscale -lSDL2 -lSDL2_image


$(call build-target, executable)


include $(BUILD_DIR)/Footer.mk
